controllers/BlocosController.php
<?
namespace app\controllers;

use app\models\CondominiosModel;
use yii\web\Controller;
use yii\data\Pagination;
use app\models\BlocosModel;
use yii;

class BlocosController extends Controller{
    public function actionListarBlocos(){
        if(yii::$app->user->isGuest){
            $this->redirect(['site/login']);
        }
        // $query = BlocosModel::find();
        $query = (new \yii\db\Query())
        ->select('bloco.id,
        cond.id as idcond,
        cond.nomeDoCondominio AS condominio,
        bloco.nomeDoBloco,
        bloco.andar,
        bloco.unidades')
        ->from(BlocosModel::tableName().' bloco')
        ->innerJoin(CondominiosModel::tableName().' cond','cond.id = bloco.condominio');

        $paginacao = new Pagination([
            'defaultPageSize'=>5,
            'totalCount'=>$query->count(),
        ]);

        $blocos = $query->orderBy('nomeDoBloco')
        ->offset($paginacao->offset)
        ->limit($paginacao->limit)
        ->all();

        return $this->render('listar-blocos', [
            'blocos'=>$blocos,
            'paginacao'=>$paginacao,
        ]);
    }
    public function actionCadastroBlocos(){
        if(yii::$app->user->isGuest){
            $this->redirect(['site/login']);
        }
        return $this->render('cadastro-blocos');
    }
    public function actionRealizaCadastroBlocos(){

        $request = \yii::$app->request;

        if($request->isPost){
            $model = new BlocosModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['blocos/listar-blocos']);
        }
        return $this->render(['cadastro-blocos']);
    }
    
    public static function listaBlocosSelect(){
        $query = BlocosModel::find();
        
        return $query->orderBy("nomeDoBloco")->all();
    }
    public static function blocosSelect($from){
        $query = BlocosModel::find();
        $data = $query->where(['condominio'=>$from])->orderBy('nomeDoBloco')->all();
        return $data;

    }
    public function actionListaBlocoApi(){
        $request = \yii::$app->request;
        $query = BlocosModel::find();
        $data = $query->where(['condominio'=>$request->post()])->orderBy('nomeDoBloco')->all();
        $dados = array();
        $i = 0;
        foreach($data as $d){
        $dados[$i]['id'] = $d['id'];
        $dados[$i]['nomeDoBloco'] = $d['nomeDoBloco'];
        $i++;
        }
        return json_encode($dados);
    }
    public function actionEditaBlocos(){
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
            $query = BlocosModel::find();
            $blocos = $query->where(['id' => $request->get()])->one();
        }
        return $this->render('edita-blocos',[
            'edit'=>$blocos
        ]);
    }
    public function actionRealizaEdicaoBlocos(){
        $request = \yii::$app->request; 
        if($request->isPost){
            
            $model = BlocosModel::findOne($request->post('id'));
            $model->attributes = $request->post();
            
         
            if($model->update()){
               return $this->redirect(['blocos/listar-blocos']);
           }else{
               return $this->redirect(['blocos/listar-blocos','msg'=>'erro']);
           }
            

        }

    }
    public function actionDeletaBlocos(){
        $request = \yii::$app->request;
        if($request->isGet){
            $model = BlocosModel::findOne($request->get('id'));
            if($model->delete()){
                return $this->redirect(['blocos/listar-blocos',
                'myAlert'=>[
                    'type'=>'success',
                    'msg'=>'Registro deletado com sucesso'
                ]]);
            }else{
                return $this->redirect(['blocos/listar-blocos',
                'myAlert'=>[
                    'type'=>'danger',
                    'msg'=>'Não foi possivel deletar o registro'
                ]]);
            }
        }
    }
    public function actionSearchBlocos(){
        $request = \yii::$app->request;
        if($request->isGet){
           
            $query = (new \yii\db\Query())
            ->select('bloco.id,
            cond.id as idcond,
            cond.nomeDoCondominio AS condominio,
            bloco.nomeDoBloco,
            bloco.andar,
            bloco.unidades')
            ->from(BlocosModel::tableName().' bloco')
            ->innerJoin(CondominiosModel::tableName().' cond','cond.id = bloco.condominio')
            ->where(['like','cond.nomeDoCondominio', $request->get('termo')]);
    
            
            $paginacao = new Pagination([
                'defaultPageSize'=>5,
                'totalCount'=>$query->count(),
            ]);
    
    
    
            $blocos = $query->orderBy('nomeDoCondominio')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->All();


        }
        return $this->render('listar-blocos',[
            'blocos'=>$blocos,
            'paginacao'=>$paginacao
        ]);
    }
}
?>

controllers/PetsController.php
<?
namespace app\controllers;

use app\models\CondominiosModel;
use app\models\MoradoresModel;
use yii\web\Controller;
use yii\data\Pagination;
use app\models\PetsModel;
use yii;

class PetsController extends Controller{
    public function actionListarPets(){
        if(yii::$app->user->isGuest){
            $this->redirect(['site/login']);
        }
        $query = (new \yii\db\query())
        ->select('
        pet.id as id,
        pet.nomeDoPet AS nomeDoPet,
        pet.tipo AS tipo,
        mor.nome AS morador,
        cond.nomeDoCondominio as condominio')
        ->from(PetsModel::tablename().' pet')
        ->innerjoin(MoradoresModel::tablename().' mor','mor.id = pet.morador')
        ->innerJoin(CondominiosModel::tableName().' cond','cond.id = mor.condominio');

        $paginacao = new Pagination([
            'defaultPageSize'=>5,
            'totalCount'=>$query->count(),
        ]);

        $pets = $query->orderBy('nomeDoPet')
        ->offset($paginacao->offset)
        ->limit($paginacao->limit)
        ->all();

        return $this->render('listar-pets', [
            'pets'=>$pets,
            'paginacao'=>$paginacao,
        ]);
    }
    public function actionCadastroPets(){
        if(yii::$app->user->isGuest){
            $this->redirect(['site/login']);
        }
        return $this->render('cadastro-pets');
    }
    public function actionRealizaCadastroPets(){
        $request = \yii::$app->request;

        if($request->isPost){
            $model = new petsModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['pets/listar-pets']);
        }
        return $this->render(['cadastro-pets']);
    }
    public static function listapetsSelect(){
        $query = petsModel::find();
        return $query->orderBy("nomeDoPet")->all();
    }
    public function actionEditaPets(){
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
            $query = petsModel::find();
            $pets = $query->where(['id' => $request->get()])->one();
        }
        return $this->render('edita-pets',[
            'edit'=>$pets
        ]);
    }
    public function actionRealizaEdicaoPets(){
        $request = \yii::$app->request; 
        if($request->isPost){
            
            $model = PetsModel::findOne($request->post('id'));
            $model->attributes = $request->post();
            
         
            if($model->update()){
               return $this->redirect(['pets/listar-pets']);
           }else{
               return $this->redirect(['pets/listar-pets','msg'=>'erro']);
           }

        }
    }
    public function actionDeletaPets(){
        $request = \yii::$app->request;
        if($request->isGet){
            $model = PetsModel::findOne($request->get('id'));
            if($model->delete()){
                return $this->redirect(['pets/listar-pets',
                'myAlert'=>[
                    'type'=>'success',
                    'msg'=>'Registro deletado com sucesso'
                ]]);
            }else{
                return $this->redirect(['pets/listar-pets',
                'myAlert'=>[
                    'type'=>'danger',
                    'msg'=>'Não foi possivel deletar o registro'
                ]]);
            }
        }
    }
    public function actionSearchPets(){
        $request = \yii::$app->request;
        if($request->isGet){
           
            $query = (new \yii\db\query())
            ->select('
            pet.id as id,
            pet.nomeDoPet AS nomeDoPet,
            pet.tipo AS tipo,
            mor.nome AS morador,
            cond.nomeDoCondominio as condominio')
            ->from(petsModel::tablename().' pet')
            ->innerjoin(MoradoresModel::tablename().' mor','mor.id = pet.morador')
            ->innerJoin(CondominiosModel::tableName().' cond','cond.id = mor.condominio') 
            ->where(['like','mor.nome', $request->get('termo')]);
    
            
            $paginacao = new Pagination([
                'defaultPageSize'=>5,
                'totalCount'=>$query->count(),
            ]);
    
    
    
            $pets = $query->orderBy('nome')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->All();
    
    
        }
        return $this->render('listar-pets',[
            'pets'=>$pets,
            'paginacao'=>$paginacao
        ]);
    }
}
?>

controllers/UnidadesController.php
<?
namespace app\controllers;

use yii\web\Controller;
use yii\data\Pagination;
use app\models\UnidadesModel;
use app\models\CondominiosModel;
use app\models\BlocosModel;
use yii;

class UnidadesController extends Controller{
    public function actionListarUnidades(){
        if(yii::$app->user->isGuest){
            $this->redirect(['site/login']);
        }
        $query = (new \yii\db\Query())
        ->select(' unid.id,
        cond.nomeDoCondominio AS condominio,
        cond.id as idcond,
        bloco.nomeDoBloco AS bloco,
        unid.nomeDaUnidade,
        unid.metragem,
        unid.vagas,
        unid.dataCadastro')
        ->from(UnidadesModel::tableName().' unid')
        ->innerJoin(CondominiosModel::tableName().' cond','cond.id = unid.condominio')
        ->innerjoin(blocosModel::tableName().' bloco','bloco.id = unid.bloco');


        $paginacao = new Pagination([
            'defaultPageSize'=>5,
            'totalCount'=>$query->count(),
        ]);

        $unidades = $query->orderBy('nomeDaUnidade')
        ->offset($paginacao->offset)
        ->limit($paginacao->limit)
        ->all();

        return $this->render('listar-unidades', [
            'unidades'=>$unidades,
            'paginacao'=>$paginacao,
        ]);
    }
    public function actionCadastroUnidades(){
        if(yii::$app->user->isGuest){
            $this->redirect(['site/login']);
        }
        return $this->render('cadastro-unidades');
    }
    public function actionRealizaCadastroUnidades(){
        $request = \yii::$app->request;

        if($request->isPost){
            $model = new UnidadesModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['unidades/listar-unidades']);
        }
        return $this->render(['cadastro-unidades']);
    }
    public static function unidadesSelect($from){
        $query = UnidadesModel::find();
        $data = $query->where(['bloco'=>$from])->orderBy('nomeDaUnidade')->all();
        return $data;

    }
    public function actionListaUnidadeApi(){
        $request = \yii::$app->request;
        $query = UnidadesModel::find();
        $data = $query->where(['bloco'=>$request->post()])->orderBy('nomeDaUnidade')->all();
        $dados = array();
        $i = 0;
        foreach($data as $d){
        $dados[$i]['id'] = $d['id'];
        $dados[$i]['nomeDaUnidade'] = $d['nomeDaUnidade'];
        $i++;
        }
        return json_encode($dados);
    }
    public function actionEditaUnidades(){
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
            $query = UnidadesModel::find();
            $unidades = $query->where(['id' => $request->get()])->one();
        }
        return $this->render('edita-unidades',[
            'edit'=>$unidades
        ]);
    }
    public function actionDeletaUnidades(){
        $request = \yii::$app->request;
        if($request->isGet){
            $model = unidadesModel::findOne($request->get('id'));
            if($model->delete()){
                return $this->redirect(['unidades/listar-unidades',
                'myAlert'=>[
                    'type'=>'success',
                    'msg'=>'Registro deletado com sucesso'
                ]]);
            }else{
                return $this->redirect(['unidades/listar-unidades',
                'myAlert'=>[
                    'type'=>'danger',
                    'msg'=>'Não foi possivel deletar o registro'
                ]]);
            }
        }
    }
    public function actionSearchUnidades(){
        $request = \yii::$app->request;
        if($request->isGet){
           
            $query = (new \yii\db\Query())
            ->select(' unid.id,
            cond.nomeDoCondominio AS condominio,
            cond.id as idcond,
            bloco.nomeDoBloco AS bloco,
            unid.nomeDaUnidade,
            unid.metragem,
            unid.vagas,
            unid.dataCadastro')
            ->from(UnidadesModel::tableName().' unid')
            ->innerJoin(CondominiosModel::tableName().' cond','cond.id = unid.condominio')
            ->innerjoin(blocosModel::tableName().' bloco','bloco.id = unid.bloco')
            ->where(['like','cond.nomeDoCondominio', $request->get('termo')]);
    
            
            $paginacao = new Pagination([
                'defaultPageSize'=>5,
                'totalCount'=>$query->count(),
            ]);
    
    
    
            $unidades = $query->orderBy('nomeDoCondominio')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->All();


        }
        return $this->render('listar-unidades',[
            'unidades'=>$unidades,
            'paginacao'=>$paginacao
        ]);
    }
}
?>

views/layouts/main.php
<?php

/** @var yii\web\View $this */
/** @var string $content */

use app\assets\AppAsset;
use app\components\alertComponent;
use app\controllers\userLogado;
use app\widgets\Alert;
use yii\bootstrap4\Breadcrumbs;
use yii\bootstrap4\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
use kartik\icons\FontAwesomeAsset;

FontAwesomeAsset::register($this);
AppAsset::register($this);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="d-flex flex-column h-100">
<?php $this->beginBody() ?>

<header>
    <?php
    NavBar::begin([
        'brandLabel' => '<img src="images/Logo-site.png" width="100px"/>',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar navbar-expand-md navbar-dark bg-dark fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav'],
        'items' => [
            [
                'label'=>'listas',
                'items'=>[
                    [
                        'label'=> 'Administradoras',
                        'url'=> ['administradoras/listar-administradoras']
                    ],
                    [
                        'label'=> 'Condominios',
                        'url'=> ['condominios/listar-condominios']
                    ],
                    [
                        'label'=> 'Conselhos',
                        'url'=> ['conselhos/listar-conselhos']
                    ],
                    [
                        'label'=> 'Blocos',
                        'url'=> ['blocos/listar-blocos']
                    ],
                    [
                        'label'=> 'Unidades',
                        'url'=> ['unidades/listar-unidades']
                    ],
                    [
                        'label'=> 'Moradores',
                        'url'=> ['moradores/listar-moradores']
                    ],
                    [
                        'label'=> 'Pets',
                        'url'=>['pets/listar-pets']
                    ]
                ],
            ],
            [
                'label'=>'Cadastrar',
                'items'=>[
                    [
                        'label'=> 'Administradoras',
                        'url'=> ['administradoras/cadastro-administradoras']
                    ],
                    [
                        'label'=> 'Condominios',
                        'url'=> ['condominios/cadastro-condominios']
                    ],
                    [
                        'label'=> 'Conselhos',
                        'url'=> ['conselhos/cadastro-conselhos']
                    ],
                    [
                        'label'=> 'Blocos',
                        'url'=> ['blocos/cadastro-blocos']
                    ],
                    [
                        'label'=> 'Unidades',
                        'url'=> ['unidades/cadastro-unidades']
                    ],
                    [
                        'label'=> 'Moradores',
                        'url'=> ['moradores/cadastro-moradores']
                    ],
                    [
                        'label'=>'Pets',
                        'url'=>['pets/cadastro-pets']
                    ]
                    ],
                ],
                [                 
                    'label'=>'lista de usuarios',
                    'url'=>['usuarios/listar-usuarios']                
                ],
                yii::$app->user->isGuest ? (
                    ['label'=>'login','url'=>['/site/login']]
                ) : (
                    '<li>'
                    .html::beginForm(['/site/logout'], 'post',['class'=>'form-inline'])
                    .html::submitButton(
                        'logout ('.yii::$app->user->identity->usuario . ')',
                        ['class'=>'btn btn-link logout']
                    )
                    .Html::endForm()
                    .'</li>'
                )
        ],
    ]);
    NavBar::end();
    ?>
</header>

<main role="main" class="flex-shrink-0 mt-5">
    <div class="container">
       
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</main>

<footer class="footer mt-auto bg-dark py-3 fixed-bottom text-muted">
    <div class="container">
        <div class="float-left">
             <p class="">&copy;ITM APPS <?= date('Y') ?></p>
        </div>
        <div class="float-right">
            
        <p><?= Yii::powered() ?></p>
        </div>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>