controllers/PetsController.php
<?
namespace app\controllers;

use app\models\CondominiosModel;
use app\models\MoradoresModel;
use yii\web\Controller;
use yii\data\Pagination;
use app\models\PetsModel;
use yii;

class PetsController extends Controller{
    public function actionListarPets(){
        if(yii::$app->user->isGuest){
            $this->redirect(['site/login']);
        }
        $query = (new \yii\db\query())
        ->select('
        pet.id as id,
        pet.nomeDoPet AS nomeDoPet,
        pet.tipo AS tipo,
        mor.nome AS morador,
        cond.nomeDoCondominio as condominio')
        ->from(PetsModel::tablename().' pet')
        ->innerjoin(MoradoresModel::tablename().' mor','mor.id = pet.morador')
        ->innerJoin(CondominiosModel::tableName().' cond','cond.id = mor.condominio');

        $paginacao = new Pagination([
            'defaultPageSize'=>5,
            'totalCount'=>$query->count(),
        ]);

        $pets = $query->orderBy('nomeDoPet')
        ->offset($paginacao->offset)
        ->limit($paginacao->limit)
        ->all();

        return $this->render('listar-pets', [
            'pets'=>$pets,
            'paginacao'=>$paginacao,
        ]);
    }
    public function actionCadastroPets(){
        if(yii::$app->user->isGuest){
            $this->redirect(['site/login']);
        }
        return $this->render('cadastro-pets');
    }
    public function actionRealizaCadastroPets(){
        $request = \yii::$app->request;

        if($request->isPost){
            $model = new petsModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['pets/listar-pets']);
        }
        return $this->render(['cadastro-pets']);
    }
    public static function listapetsSelect(){
        $query = petsModel::find();
        return $query->orderBy("nomeDoPet")->all();
    }
    public function actionEditaPets(){
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
            $query = petsModel::find();
            $pets = $query->where(['id' => $request->get()])->one();
        }
        return $this->render('edita-pets',[
            'edit'=>$pets
        ]);
    }
    public function actionRealizaEdicaoPets(){
        $request = \yii::$app->request; 
        if($request->isPost){
            
            $model = PetsModel::findOne($request->post('id'));
            $model->attributes = $request->post();
            
         
            if($model->update()){
               return $this->redirect(['pets/listar-pets']);
           }else{
               return $this->redirect(['pets/listar-pets','msg'=>'erro']);
           }

        }
    }
    public function actionDeletaPets(){
        $request = \yii::$app->request;
        if($request->isGet){
            $model = PetsModel::findOne($request->get('id'));
            if($model->delete()){
                return $this->redirect(['pets/listar-pets',
                'myAlert'=>[
                    'type'=>'success',
                    'msg'=>'Registro deletado com sucesso'
                ]]);
            }else{
                return $this->redirect(['pets/listar-pets',
                'myAlert'=>[
                    'type'=>'danger',
                    'msg'=>'Não foi possivel deletar o registro'
                ]]);
            }
        }
    }
    public function actionSearchPets(){
        $request = \yii::$app->request;
        if($request->isGet){
           
            $query = (new \yii\db\query())
            ->select('
            pet.id as id,
            pet.nomeDoPet AS nomeDoPet,
            pet.tipo AS tipo,
            mor.nome AS morador,
            cond.nomeDoCondominio as condominio')
            ->from(petsModel::tablename().' pet')
            ->innerjoin(MoradoresModel::tablename().' mor','mor.id = pet.morador')
            ->innerJoin(CondominiosModel::tableName().' cond','cond.id = mor.condominio') 
            ->where(['like','mor.nome', $request->get('termo')]);
    
            
            $paginacao = new Pagination([
                'defaultPageSize'=>5,
                'totalCount'=>$query->count(),
            ]);
    
    
    
            $pets = $query->orderBy('nome')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->All();
    
    
        }
        return $this->render('listar-pets',[
            'pets'=>$pets,
            'paginacao'=>$paginacao
        ]);
    }
}
?>

views/pets/cadastro-pets.php
<?

use app\controllers\CondominiosController;
use app\controllers\MoradoresController;
use yii\helpers\Url;

?>
<div class="row">
    <div class="col-12 pb-5">
        <h1 class="col-12 col-sm-12 col-md-12 text-center">Formulario de cadastro de Pet</h1>
    </div>
</div>

<form class="form-row formPets" action="<?echo Url::to(['pets/realiza-cadastro-pets'])?>" method="POST">
   
    <div class="col-12 col-md-12 from-group mt-2">
        <input class="col-12  text-center mb-2 bg-custom form-control" type="text" name="nomeDoPet" placeholder="Nome do Pet" value=""required>
    </div>
    <div class="col-12 col-md-12 text-center from-group">
    <select class="col-12 text-center bg-custom custom-select" name="tipo">
        <option>tipo</option>
        <option value="cachorro">Cachorro</option>
        <option value="gato">Gato</option>
        <option value="passaro">Passaro</option>
    </select>
    </div>
    <div class="col-12 col-md-12 text-center from-group mt-2 mb-2">
        <select name="condominio"class="fromMorCond col-12 bg-custom text-center custom-select">
            <option>Condominio</option>
            <?foreach(CondominiosController::listaCondominiosSelect() as $ch=>$val){?>
            <option value="<?=$val['id']?>"><?=$val['nomeDoCondominio']?></option>
            <?}?>
        </select>
    </div>
    <div class="col-12 col-md-12 text-center from-group">
    <select class="col-12 text-center bg-custom custom-select fromMor" name="morador">
      
    </select>
    </div>

    <input type="hidden" name="<?= \Yii::$app->request->csrfParam;?>" value="<?= yii::$app->request->csrfToken;?>">
    
    <div class="col-12 col-md-12 text-center">
        <button type="submit" class="btn bg-blue btn-dark mt-2 px-5 buttonEnviar">enviar</button>
        
    </div>
</form>

views/pets/edita-pets.php
<?

use app\components\selectedComponent;
use yii\helpers\url;
use app\controllers\CondominiosController;
use app\controllers\MoradoresController;

?>
<div class="row">
    <div class="col-12 pb-5">
        <h1 class="col-12 col-sm-12 col-md-12 text-center">Formulario de Edição</h1>
    </div>
</div>

<form class="form-row formPets" action="<?=Url::to(['pets/realiza-edicao-pets'])?>" method="POST">
    <div class="col-12 col-md-12 text-center from-group mb-2">
        <select name="condominio" class="col-6 text-center custom-select bg-custom fromMorCond">
            <option>Condominio</option>
            <? foreach (CondominiosController::listaCondominiosSelect() as $ch => $val) { ?>
                <option value="<?= $val['id'] ?>"<?= selectedComponent::isSelected($val['id'],$edit['condominio']) ?>><?=$val['nomeDoCondominio']?></option>
            <? } ?>
        </select>
    </div>

    <div class="col-12 col-md-12 text-center from-group mb-2">
        <select name="morador" class="fromMor col-6 text-center custom-select bg-custom">
        <? foreach (MoradoresController::moradoresSelect($edit['condominio']) as $mor){?>
              <option value="<?= $mor['id'] ?>"<?= selectedComponent::isSelected($mor['id'],$edit['morador']) ?>><?= $mor['nome'] ?></option>
        <?}?>

        </select>
    </div>

    <div class="col-12 text-center">
        <input class="col-6 bg-custom form-control text-center" type="text" name="nomeDoPet" placeholder="Nome do pet" value="<?=$edit['nomeDoPet']?>" required>
    </div>
    <div class="col-12 text-center">
        <input class="col-6  bg-custom form-control text-center" type="text" name="tipo" placeholder="Tipo do pet" value="<?=$edit['tipo']?>" required>
    </div>

    

    
    
    
    <div class="col-12 text-center">
    <input type="hidden" name="id" value="<?=$edit['id']?>">
    <input type="hidden" name="<?= \Yii::$app->request->csrfParam;?>" value="<?= yii::$app->request->csrfToken;?>">
    </div>

    <div class="col-12 col-md-12 text-center">
        
       
        <button type="submit" class="btn bg-blue btn-dark mt-2 px-5 buttonEnviar">enviar</button>

    </div>
</form>

views/pets/listar-pets.php
<?

use app\components\ModalComponent;
use yii\widgets\LinkPager;
use yii\helpers\Url;


$url_site = url::base($schema = true);
?>


<div class="col-12 text-center">
    <h1>Lista de Pets</h1>
</div>
<form id="filtro" method="GET" class="form-row mt-5 justify-content-center">
    <div class="col-12 col-sm-10">
      <div class="input-group mb-2">
        <div class="input-group-prepend">
          <div class="input-group-text text-white bg-dark">Nome Do Morador:</div>
        </div>
        <input type="hidden" name="r" value="pets/search-pets">
        <input type="search"aria-label="Search" class="form-control" name="termo">
      </div>
    </div>
    <div class="">
        <button type="submit" class="btn btn-primary">Pesquisar</button>
        <a href="<?=$url_site?>?r=pets/listar-pets" class="btn btn-danger">Cancelar</a>
    </div>
    </form>
<div class="row">
    <div class="col-12 col-md-12">
        <table class="table table-responsive-md table-dark table-striped"id="listaPet">
            <th>Nome do pet</th>
            <th>Tipo</th>
            <th>Dono/Morador</th>
            <th>Condominio</th>
            <th><a href="<?=$url_site?>?r=pets/cadastro-pets" class="btn btn-light"><i class="icofont-ui-add"> Cadastrar</i></a></th>
            <?
           
           foreach($pets as $value){?>
            <tr data-id="<?=$value['id']?>">
                <td><?=$value['nomeDoPet']?></td>
                <td><?=$value['tipo']?></td>
                <td><?=$value['morador']?></td>
                <td><?=$value['condominio']?></td>
                <td>
                    <a href="<?=$url_site?>?r=pets/edita-pets&id=<?=$value['id']?>"name="id" class="text-white openModal"><i class="bi bi-pen-fill"></i></a> 
                    <a href="<?=$url_site?>?r=pets/deleta-pets&id=<?=$value['id']?>"name="remove" data-id="<?=$value['id']?>"class="text-white mr-4 removerPet"><i class="bi bi-trash3-fill"></i></a>
                </td>
            </tr>  
            <?}?>
            <tr>
                <td colspan="2">&nbsp;</td>
               
                <td colspan="3" class="text-right ">Total de Registros: <small class="badge badge-light totalRegistros"><?=$paginacao->totalCount?></small></td>
    
            </tr>
            
        </table>
        <div class="row">
            <?=LinkPager::widget(
                [
                'pagination'=>$paginacao,
                'linkContainerOptions'=>[
                    'class'=>'page-item'
                ],
                'linkOptions'=>[
                    'class'=>'page-link'
                ],
                'disabledListItemSubTagOptions'=>[
                    'class'=>'page-link'                
                ]
                ]
            )
                ?>

        </div>
    </div>
</div>
<?=ModalComponent::modal()?>