controllers/CondominiosController.php
<?
namespace app\controllers;

use app\components\MascaraComponent;
use app\models\AdministradorasModel;
use yii\web\Controller;
use yii\data\Pagination;
use app\models\CondominiosModel;
use yii;
use app\controllers\UserLogado;

class CondominiosController extends Controller{
    

    public function actionListarCondominios(){
        if(yii::$app->user->isGuest){
            $this->redirect(['site/login']);
        }
        
      
       
        $query = (new \yii\db\Query())
        ->select(['cond.id', 'cond.nomeDoCondominio', 'cond.bloco', 'cond.logradouro', 'cond.numero','cond.bairro', 'cond.cidade', 'cond.estado', 'cond.cep', 'adm.nomeDaAdm AS adm'])
        ->from(CondominiosModel::tableName().' cond')
        ->innerJoin(AdministradorasModel::tableName().' adm','adm.id = cond.adm');
    
        $paginacao = new Pagination([
            'defaultPageSize'=>5,
            'totalCount'=>$query->count(),
        ]);



        $Condominios = $query->orderBy('nomeDoCondominio')
        ->offset($paginacao->offset)
        ->limit($paginacao->limit)
        ->all();

        return $this->render('listar-condominios', [
            'condominios'=>$Condominios,
            'paginacao'=>$paginacao,
        ]);
    }
    public function actionCadastroCondominios(){
        if(yii::$app->user->isGuest){
            $this->redirect(['site/login']);
        }
        
        return $this->render('cadastro-condominios');
    }
    public function actionRealizaCadastroCondominios(){

        $request = \yii::$app->request;

        if($request->isPost){
            $model = new CondominiosModel();
            foreach($request->post() as $field=>$value){
                if($field == 'cep'){
                    $getMany[$field] = mascaraComponent::desMask($value);
                }else{
                    $getMany[$field] = $value;
                }
            }
            $model->attributes = $getMany();
            $model->save();
            return $this->redirect(['condominios/listar-condominios']);
        }
        return $this->render(['cadastro-condominios']);
    }
    public static function listaCondominiosSelect(){
        
        $query = CondominiosModel::find();
        return $query->orderBy("nomeDoCondominio")->all();
    }
    public function actionEditaCondominios(){
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
            $query = CondominiosModel::find();
            $condominios = $query->where(['id' => $request->get()])->one();
        }
        return $this->render('edita-condominios',[
            'edit'=>$condominios
        ]);
    }
    public function actionRealizaEdicaoCondominios(){
        $request = \yii::$app->request; 
        if($request->isPost){
            
            $model = CondominiosModel::findOne($request->post('id'));
            $model->attributes = $request->post();
            
         
            if($model->update()){
               return $this->redirect(['condominios/listar-condominios']);
           }else{
               return $this->redirect(['condominios/listar-condominios','msg'=>'erro']);
           }
            

        }

    }
    public function actionDeletaCondominios(){
        $request = \yii::$app->request;
        if($request->isGet){
            $model = CondominiosModel::findOne($request->get('id'));
            if($model->delete()){
                return $this->redirect(['condominios/listar-condominios',
                'myAlert'=>[
                    'type'=>'success',
                    'msg'=>'Registro deletado com sucesso'
                ]]);
            }else{
                return $this->redirect(['condominios/listar-condominios',
                'myAlert'=>[
                    'type'=>'danger',
                    'msg'=>'Não foi possivel deletar o registro'
                ]]);
            }
        }
    }
    public static function numeroDeMoradores(){
        $query = yii::$app->db->createCommand('SELECT
        cond.nomeDoCondominio AS conds,
        COUNT(mor.id) AS mors
        FROM
        jz_morador mor
        INNER JOIN jz_condominio cond ON cond.id = mor.condominio
        GROUP BY conds')->queryAll();
        return $query;
    }
    //retorna o total de condominios cadastrados
    public static function totalConds(){
        $query = yii::$app->db->createCommand('SELECT
        COUNT(id)   
        FROM jz_condominio')->queryScalar();
        return $query;
    }
    
    //pesquisa por nome do cond?
    public function actionSearchCond(){
        $request = \yii::$app->request;
        if($request->isGet){
           
            $query = (new \yii\db\Query())
            ->select(['cond.id', 'cond.nomeDoCondominio', 'cond.bloco', 'cond.logradouro', 'cond.numero','cond.bairro', 'cond.cidade', 'cond.estado', 'cond.cep', 'adm.nomeDaAdm AS adm'])
            ->from(CondominiosModel::tableName().' cond')
            ->innerJoin(AdministradorasModel::tableName().' adm','adm.id = cond.adm')
            ->where(['like','nomeDoCondominio', $request->get('termo')]);
            
            $paginacao = new Pagination([
                'defaultPageSize'=>5,
                'totalCount'=>$query->count(),
            ]);
    
    
    
            $Condominios = $query->orderBy('nomeDoCondominio')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->All();


        }
        return $this->render('listar-condominios',[
            'condominios'=>$Condominios,
            'paginacao'=>$paginacao
        ]);
    }
    
    
}
?>

views/condominios/cadastro-condominios.php
<?

use app\components\estadosComponent;
use yii\helpers\Url;
use app\controllers\AdministradorasController;

?>

<div class="row">
    <div class="col-12 pb-5">
        <h1 class="col-12 col-sm-12 col-md-12 text-center">Formulario de Condominio</h1>
    </div>
</div>

<form class="form-row formCondominio" action="<?= Url::to(['condominios/realiza-cadastro-condominios'])?>" method="POST">
    <div class="col-12 col-sm-12">
        <input class="col-12 text-center form-control bg-custom" type="text" name="nomeDoCondominio" placeholder="Nome do condominio" value=""required>
    </div>
    <div class="col-12 col-sm-12">
        <input class="col-12 text-center form-control bg-custom" type="text" name="bloco" placeholder="Quantidade de blocos" value="">
    </div>
    <div class="col-12 col-sm-12 ">
        <input class="col-12 text-center form-control bg-custom cep" type="text" name="cep" placeholder="CEP" value="">
    </div>
    
    <div class="col-12 col-sm-12">
        <input class="col-12 text-center form-control bg-custom logradouro" type="text" name="logradouro"placeholder="Logradouro"value="">
    </div>
    <div class="col-12 col-sm-12">
        <input class="col-12 text-center form-control bg-custom" type="text" name="numero"placeholder="N°"value="">
    </div>
    <div class="col-12 col-sm-12">
        <input class="col-12 text-center form-control bg-custom bairro" type="text" name="bairro" placeholder="Bairro"value="">
    </div>
    <div class="col-12 col-sm-12">
        <input class="col-12 text-center form-control bg-custom cidades" type="text" name="cidade" placeholder="cidade"value="">
    </div>
    <div class="col-12 col-sm-12">
       <select class="col-12 col-sm-12 custom-select bg-custom mt-2 text-center fromEstados" name="estado">
           <option>estado</option>
           <?foreach(estadosComponent::estados() as $sig=>$uf){?>
          <option value="<?=$sig?>"><?=$uf?></option>
            <?}?>
       </select>
    </div>
    <select class="col-12 col-sm-12 text-center custom-select bg-custom mt-2 " name="adm">
        <option >Administradora</option>
        <?foreach(AdministradorasController::listaAdministradorasSelect() as $adm){?>
        <option value="<?=$adm['id']?>"><?=$adm['nomeDaAdm'];?></option>
        <?}?>
    </select>
    <input type="hidden" name="<?= \Yii::$app->request->csrfParam;?>" value="<?= yii::$app->request->csrfToken;?>">
    <div class="col-12 col-sm-12 text-center">
        
        <button type="submit" class="btn bg-blue btn-dark mt-2 px-5 buttonEnviar">enviar</button>
        
    </div>
</form>

views/condominios/edita-condominios.php
<?

use app\components\estadosComponent;
use app\components\mascaraComponent;
use app\components\selectedComponent;
use yii\helpers\url;
use app\controllers\AdministradorasController;

?>

<div class="row">
    <div class="col-12 pb-5">
        <h1 class="col-12 col-sm-12 col-md-12 text-center">Formulario de Edição</h1>
    </div>
</div>

<form class="form-row formCondominio" action="<?= Url::to(['condominios/realiza-edicao-condominios'])?>" method="POST">
    <div class="col-12 col-md-12 text-center">
        <label for="nomeDoCondominio">Nome do condominio</label>
        <input class="col-12 form-control bg-custom text-center " type="text" name="nomeDoCondominio" placeholder="Nome do condominio" value="<?=$edit['nomeDoCondominio']?>"required>
    </div>
    <div class="col-12 col-md-12 text-center">
    <label for="bloco">Qtd. blocos</label>
        <input class="col-12 text-center  form-control bg-custom" type="text" name="bloco" placeholder="Quantidade de blocos" value="<?=$edit['bloco']?>">
    </div>
    <div class="col-12 col-md-12 text-center">
    <label for="cep">CEP</label>
        <input class="col-12 text-center  form-control bg-custom cep" type="text" name="cep" placeholder="CEP" value="<?=mascaraComponent::mascara($edit['cep'], 'cep')?>">
    </div>
    
    <div class="col-12 col-md-12 text-center">
    <label for="logradouro">Logradouro</label>
        <input class="col-12 text-center  form-control logradouro" type="text" name="logradouro"placeholder="Logradouro"value="<?=$edit['logradouro']?>">
    </div>
    <div class="col-12 col-md-12 text-center">
    <label for="numero">Nº</label>
        <input class="col-12 text-center  form-control" type="text" name="numero"placeholder="N°"value="<?=$edit['numero']?>">
    </div>
    <div class="col-12 col-md-12 text-center">
    <label for="bairro">Bairro</label>
        <input class="col-12 text-center  form-control bairro" type="text" name="bairro"placeholder="Bairro"value="<?=$edit['bairro']?>">
    </div>
    <div class="col-12 col-md-12 text-center">
    <label for="cidade">Cidade</label>
        <input class="col-12 text-center  form-control cidades" type="text" name="cidade"placeholder="cidade"value="<?=$edit['cidade']?>">
    </div>
    <div class="col-12 col-md-12 text-center">
    <label for="estado">Estado</label>
       <select class="col-12 col-md-12 text-center custom-select fromEstado" name="estado">
           <option>estado</option>
           <?foreach(estadosComponent::estados() as $sig=>$uf){?>
          <option value="<?=$sig?>"<?=selectedComponent::isSelected($sig, $edit['estado'])?>><?=$uf?></option>
            <?}?>
       </select>
    </div>
    <div class="col-12 col-md-12  text-center">
    <label for="adm">Administradora</label>
        <select class="col-12 col-sm-12 text-center custom-select" name="adm">
        <? foreach (AdministradorasController::listaAdministradorasSelect() as $adm) { ?>
                    <option value="<?= $adm['id'] ?>"<?= selectedComponent::isSelected($adm['id'],$edit['adm']) ?>><?=$adm['nomeDaAdm']?></option>
                <? } ?>
        </select>

    </div>
    <input type="hidden" name="id" value="<?=$edit['id']?>">
    <input type="hidden" name="<?= \Yii::$app->request->csrfParam;?>" value="<?= yii::$app->request->csrfToken;?>">
    <div class="col-12 col-md-12 text-center">
   
        <button type="submit" class="btn bg-blue btn-dark mt-2 px-5 buttonEnviar">enviar</button>
        
    </div>
</form>

views/condominios/listar-condominios.php
<?

use app\components\ModalComponent;
use app\controllers\AdministradorasController;
use app\controllers\CondominiosController;
use app\controllers\MaskController;
use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\helpers\Url;

$url_site = url::base(true);
?>

<div class="col-12 text-center">
    <h1>Lista de condominios</h1>
</div>
    <form id="filtro" method="GET" class="form-row mt-5 justify-content-center">
    <div class="col-12 col-sm-10">
      <div class="input-group mb-2">
        <div class="input-group-prepend">
          <div class="input-group-text text-white bg-dark">Nome Do Condominio:</div>
        </div>
        <input type="hidden" name="r" value="condominios/search-cond">
        <input type="search"aria-label="Search" class="form-control" name="termo">
      </div>
    </div>
    <div class="">
        <button type="submit" class="btn btn-primary">Pesquisar</button>
        <a href="<?=$url_site?>?r=condominios/listar-condominios" class="btn btn-danger">Cancelar</a>
    </div>
    </form>
<div class="row">
    <div class="col-12 col-md-12 ">


        <table class="table table-responsive-md table-dark table-striped" id="listaCondominios">
            <th>Condominio</th>
            <th>Qtd. de blocos</th>
            <th>Logradouro</th>
            <th>N°</th>
            <th>Bairro</th>
            <th>Cidade</th>
            <th>estado</th>
            <th>CEP</th>
            <th>Adiministradora</th>
            <th><a href="<?= $url_site ?>?r=condominios/cadastro-condominios" class="btn btn-light"><i class="icofont-ui-add"> Cadastrar</i></a></th>
            <?

            foreach ($condominios as $value) {
            ?>
                <tr data-id="<?= $value['id'] ?>">
                    <td><?= $value['nomeDoCondominio'] ?></td>
                    <td><?= $value['bloco'] ?></td>
                    <td><?= $value['logradouro'] ?></td>
                    <td><?= $value['numero'] ?></td>
                    <td><?= $value['bairro'] ?></td>
                    <td><?= $value['cidade'] ?></td>
                    <td><?= $value['estado'] ?></td>
                    <td><?= maskController::Mask($value['cep'], 'cep') ?></td>
                    <td><?= $value['adm'] ?></td>
                    <td>
                        <a href="<?= $url_site ?>?r=condominios/edita-condominios&id=<?= $value['id'] ?>" name="id" class="text-white openModal"><i class="bi bi-pen-fill"></i></a>
                        <a href="<?= $url_site ?>?r=condominios/deleta-condominios&id=<?= $value['id'] ?>" name="remove" data-id="<?= $value['id'] ?>" class="text-white mr-4 removerCondominio"><i class="bi bi-trash3-fill"></i></a>
                    </td>

                </tr>
            <? } ?>
            <tr>
                <td colspan="4">&nbsp;</td>

                <td colspan="6" class="text-right ">Total de Registros: <small class="badge badge-light totalRegistros"><?= $paginacao->totalCount ?> </small></td>

            </tr>
        </table>

        <div class="row">
            <?= LinkPager::widget(
                [
                    'pagination' => $paginacao,
                    'linkContainerOptions' => [
                        'class' => 'page-item'
                    ],
                    'linkOptions' => [
                        'class' => 'page-link'
                    ],
                    'disabledListItemSubTagOptions' => [
                        'class' => 'page-link'
                    ]
                ]
            )
            ?>

        </div>

    </div>
</div>
<?=ModalComponent::modal() ?>