controllers/BlocosController.php
<?
namespace app\controllers;

use app\models\CondominiosModel;
use yii\web\Controller;
use yii\data\Pagination;
use app\models\BlocosModel;
use yii;

class BlocosController extends Controller{
    public function actionListarBlocos(){
        if(yii::$app->user->isGuest){
            $this->redirect(['site/login']);
        }
        // $query = BlocosModel::find();
        $query = (new \yii\db\Query())
        ->select('bloco.id,
        cond.id as idcond,
        cond.nomeDoCondominio AS condominio,
        bloco.nomeDoBloco,
        bloco.andar,
        bloco.unidades')
        ->from(BlocosModel::tableName().' bloco')
        ->innerJoin(CondominiosModel::tableName().' cond','cond.id = bloco.condominio');

        $paginacao = new Pagination([
            'defaultPageSize'=>5,
            'totalCount'=>$query->count(),
        ]);

        $blocos = $query->orderBy('nomeDoBloco')
        ->offset($paginacao->offset)
        ->limit($paginacao->limit)
        ->all();

        return $this->render('listar-blocos', [
            'blocos'=>$blocos,
            'paginacao'=>$paginacao,
        ]);
    }
    public function actionCadastroBlocos(){
        if(yii::$app->user->isGuest){
            $this->redirect(['site/login']);
        }
        return $this->render('cadastro-blocos');
    }
    public function actionRealizaCadastroBlocos(){

        $request = \yii::$app->request;

        if($request->isPost){
            $model = new BlocosModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['blocos/listar-blocos']);
        }
        return $this->render(['cadastro-blocos']);
    }
    
    public static function listaBlocosSelect(){
        $query = BlocosModel::find();
        
        return $query->orderBy("nomeDoBloco")->all();
    }
    public static function blocosSelect($from){
        $query = BlocosModel::find();
        $data = $query->where(['condominio'=>$from])->orderBy('nomeDoBloco')->all();
        return $data;

    }
    public function actionListaBlocoApi(){
        $request = \yii::$app->request;
        $query = BlocosModel::find();
        $data = $query->where(['condominio'=>$request->post()])->orderBy('nomeDoBloco')->all();
        $dados = array();
        $i = 0;
        foreach($data as $d){
        $dados[$i]['id'] = $d['id'];
        $dados[$i]['nomeDoBloco'] = $d['nomeDoBloco'];
        $i++;
        }
        return json_encode($dados);
    }
    public function actionEditaBlocos(){
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
            $query = BlocosModel::find();
            $blocos = $query->where(['id' => $request->get()])->one();
        }
        return $this->render('edita-blocos',[
            'edit'=>$blocos
        ]);
    }
    public function actionRealizaEdicaoBlocos(){
        $request = \yii::$app->request; 
        if($request->isPost){
            
            $model = BlocosModel::findOne($request->post('id'));
            $model->attributes = $request->post();
            
         
            if($model->update()){
               return $this->redirect(['blocos/listar-blocos']);
           }else{
               return $this->redirect(['blocos/listar-blocos','msg'=>'erro']);
           }
            

        }

    }
    public function actionDeletaBlocos(){
        $request = \yii::$app->request;
        if($request->isGet){
            $model = BlocosModel::findOne($request->get('id'));
            if($model->delete()){
                return $this->redirect(['blocos/listar-blocos',
                'myAlert'=>[
                    'type'=>'success',
                    'msg'=>'Registro deletado com sucesso'
                ]]);
            }else{
                return $this->redirect(['blocos/listar-blocos',
                'myAlert'=>[
                    'type'=>'danger',
                    'msg'=>'Não foi possivel deletar o registro'
                ]]);
            }
        }
    }
    public function actionSearchBlocos(){
        $request = \yii::$app->request;
        if($request->isGet){
           
            $query = (new \yii\db\Query())
            ->select('bloco.id,
            cond.id as idcond,
            cond.nomeDoCondominio AS condominio,
            bloco.nomeDoBloco,
            bloco.andar,
            bloco.unidades')
            ->from(BlocosModel::tableName().' bloco')
            ->innerJoin(CondominiosModel::tableName().' cond','cond.id = bloco.condominio')
            ->where(['like','cond.nomeDoCondominio', $request->get('termo')]);
    
            
            $paginacao = new Pagination([
                'defaultPageSize'=>5,
                'totalCount'=>$query->count(),
            ]);
    
    
    
            $blocos = $query->orderBy('nomeDoCondominio')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->All();


        }
        return $this->render('listar-blocos',[
            'blocos'=>$blocos,
            'paginacao'=>$paginacao
        ]);
    }
}
?>

views/blocos/cadastro-blocos.php
<?
use yii\helpers\Url;
use app\controllers\CondominiosController;

?>

<div class="row">
    <div class="col-12 pb-5">
        <h1 class="col-12 col-sm-12 col-md-12 text-center">Formulario de cadastro</h1>
    </div>
</div>

<form class="form-row formBloco" action="<?= Url::to(['blocos/realiza-cadastro-blocos'])?>" method="POST">
    <div class="col-12 col-md-12 text-center">
    <select class="col-12 text-center custom-select bg-custom" name="condominio">
           <option>condominio</option>
        <?foreach(CondominiosController::listaCondominiosSelect() as $cond){?>
        <option value="<?=$cond['id']?>"><?=$cond['nomeDoCondominio'];?></option>
        <?}?>
       </select>
    </div>
    <div class="col-12 col-md-12 text-center mt-2">
        <input class="col-12 text-center mb-2 form-control bg-custom" type="text" name="nomeDoBloco" placeholder="Nome do bloco" value=""required>
    </div>
    <div class="col-12 col-md-12 text-center">
        <input class="col-12 text-center form-control bg-custom" type="text" name="andar" placeholder="Quantos andares?" value=""required>
    </div>
    <div class="col-12 col-md-12 text-center mt-2">
        <input class="col-12 text-center form-control bg-custom" type="text" name="unidades"placeholder="Quantidade de unidades por andar" value=""required>
    </div>
    <input type="hidden" name="<?= \Yii::$app->request->csrfParam;?>" value="<?= yii::$app->request->csrfToken;?>">
    <div class="col-12 col-md-12 text-center">
        <button type="submit" class="btn bg-blue btn-dark mt-2 px-5 buttonEnviar">enviar</button>
        
    </div>
</form>

views/blocos/edita-blocos.php
<?

use app\components\selectedComponent;
use yii\helpers\url;
use app\controllers\CondominiosController;

?>

<div class="row">
    <div class="col-12 pb-5">
        <h1 class="col-12 col-sm-12 col-md-12 text-center">Formulario de Edição</h1>
    </div>
</div>

<form class="form-row formBloco" action="<?= Url::to(['blocos/realiza-edicao-blocos'])?>" method="POST">
    <div class="col-12 col-md-12 text-center from-group">
    <select class="col-6 text-center custom-select bg-custom" name="condominio">
           <option>condominio</option>
           <? foreach (CondominiosController::listaCondominiosSelect() as $ch => $val) { ?>
                <option value="<?= $val['id'] ?>"<?= selectedComponent::isSelected($val['id'],$edit['condominio']) ?>><?=$val['nomeDoCondominio']?></option>
            <? } ?>
       </select>
    </div>
    <div class="col-12 col-md-12 d-flex justify-content-center from-group mt-2">
        <input class="col-6 text-center form-control bg-custom mb-2" type="text" name="nomeDoBloco" placeholder="Nome do bloco" value="<?=$edit['nomeDoBloco']?>"required>
    </div>
    <div class="col-12 col-md-12 d-flex justify-content-center from-group">
        <input class="col-6 text-center form-control bg-custom" type="text" name="andar" placeholder="Quantos andares?" value="<?=$edit['andar']?>"required>
    </div>
    <div class="col-12 col-md-12 d-flex justify-content-center from-group mt-2">
        <input class="col-6 text-center form-control bg-custom" type="text" name="unidades"placeholder="Quantidade de unidades por andar" value="<?=$edit['unidades']?>"required>
    </div>
    <input type="hidden" name="id" value="<?=$edit['id']?>">
    <input type="hidden" name="<?= \Yii::$app->request->csrfParam;?>" value="<?= yii::$app->request->csrfToken;?>">
    <div class="col-12 col-md-12 text-center">
       
        <button type="submit" class="btn bg-blue btn-dark mt-2 px-5 buttonEnviar">enviar</button>
    </div>
</form>

views/blocos/listar-blocos.php
<?

use app\components\ModalComponent;
use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\helpers\Url;

$url_site = url::base($schema = true);
?>
<div class="col-12 text-center">
    <h1>Lista de blocos</h1>
</div>
<form id="filtro" method="GET" class="form-row mt-5 justify-content-center">
    <div class="col-12 col-sm-10">
      <div class="input-group mb-2">
        <div class="input-group-prepend">
          <div class="input-group-text text-white bg-dark">Nome Do Condominio:</div>
        </div>
        <input type="hidden" name="r" value="blocos/search-blocos">
        <input type="search"aria-label="Search" class="form-control" name="termo">
      </div>
    </div>
    <div class="">
        <button type="submit" class="btn btn-primary">Pesquisar</button>
        <a href="<?=$url_site?>?r=blocos/listar-blocos" class="btn btn-danger">Cancelar</a>
    </div>
    </form>
<div class="row">
    <div class="col-12 col-md-12">
        <table class="table table-responsive-md table-dark table-striped"id="listaBloco">
            <th>Condominio</th>
            <th>Nome do Bloco</th>
            <th>qtd. de andares</th>
            <th>qtd. de unidades por andar</th>
            <th><a href="<?=$url_site?>?r=blocos/cadastro-blocos" class="btn btn-light"><i class="icofont-ui-add"> Cadastrar</i></a></th>
            <?
            
            foreach($blocos as $ch=>$value){?>
            <tr data-id="<?=$value['id']?>">
                <td><?=$value['condominio']?></td>
                <td><?=$value['nomeDoBloco']?></td>
                <td><?=$value['andar']?></td>
                <td><?=$value['unidades']?></td>
                
                <td>
                    <a href="<?=$url_site?>?r=blocos/edita-blocos&id=<?=$value['id']?>"name="id" class="text-white openModal"><i class="bi bi-pen-fill"></i></a> 
                    <a href="<?=$url_site?>?r=blocos/deleta-blocos&id=<?=$value['id']?>"name="remove" data-id="<?=$value['id']?>"class="text-white mr-4 removerBloco"><i class="bi bi-trash3-fill"></i></a>
                </td>
                
            </tr>  
            <?}?>
            <tr>
                <td colspan="2">&nbsp;</td>
               
                <td colspan="3" class="text-right ">Total de Registros: <small class="badge badge-light totalRegistros"><?=$paginacao->totalCount?></small></td>

            </tr>
        </table>
        <div class="row">
            <?=LinkPager::widget(
                [
                'pagination'=>$paginacao,
                'linkContainerOptions'=>[
                    'class'=>'page-item'
                ],
                'linkOptions'=>[
                    'class'=>'page-link'
                ],
                'disabledListItemSubTagOptions'=>[
                    'class'=>'page-link'                
                ]
                ]
            )
                ?>
    </div>
</div>
<?=ModalComponent::modal()?>